### ISSUE TITLE
[support] align distribution

### ISSUE THREAD

**Issue by mirceanis** [uport-project/uport-android-sdk#3]
The sdk is using jitpack for distribution but the bundling code is not really aligned to that.
* mismatches in groupID
* demo app should also demo loading
* version used in build.gradle files needs to be kept in sync with git tags

**Comment by pelle** [comment]
@mirceanis please decide on priority for this depending on other sprint work

**Comment by mirceanis** [comment]
It's not a priority but it's a good starting point for anyone who wishes to contribute

**Comment by mirceanis** [comment]
this was fixed in #68
